name: pgembed
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - attrs=22.1.0
  - biopython=1.78
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - libcxx=14.0.6
  - libffi=3.4.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - numpy=1.23.4
  - numpy-base=1.23.4
  - openssl=1.1.1s
  - packaging=21.3
  - pip=22.3.1
  - pluggy=1.0.0
  - prodigal=2.6.3
  - py=1.11.0
  - pyparsing=3.0.9
  - pytest=7.1.2
  - python=3.8.15
  - readline=8.2
  - setuptools=65.5.1
  - six=1.16.0
  - sqlite=3.40.0
  - tk=8.6.12
  - tomli=2.0.1
  - tzdata=2022g
  - wheel=0.37.1
  - xz=5.2.8
  - zlib=1.2.13
  - pip:
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - alabaster==0.7.12
    - allennlp==0.9.0
    - async-timeout==4.0.2
    - babel==2.11.0
    - base58==2.1.1
    - blis==0.2.4
    - boto3==1.26.28
    - botocore==1.29.28
    - cached-path==1.1.6
    - cachetools==5.2.0
    - catalogue==2.0.8
    - certifi==2022.12.7
    - charset-normalizer==2.1.1
    - click==8.1.3
    - commonmark==0.9.1
    - conllu==1.3.1
    - contourpy==1.0.6
    - cycler==0.11.0
    - cymem==2.0.7
    - datasets==2.7.1
    - dill==0.3.6
    - docker-pycreds==0.4.0
    - docutils==0.19
    - editdistance==0.6.1
    - fairscale==0.4.6
    - filelock==3.7.1
    - flaky==3.7.0
    - flask==2.2.2
    - flask-cors==3.0.10
    - fonttools==4.38.0
    - frozenlist==1.3.3
    - fsspec==2022.11.0
    - ftfy==6.1.1
    - gevent==22.10.2
    - gitdb==4.0.10
    - gitpython==3.1.29
    - google-api-core==2.11.0
    - google-auth==2.15.0
    - google-cloud-core==2.3.2
    - google-cloud-storage==2.7.0
    - google-crc32c==1.5.0
    - google-resumable-media==2.4.0
    - googleapis-common-protos==1.57.0
    - greenlet==2.0.1
    - h5py==2.10.0
    - huggingface-hub==0.10.1
    - idna==3.4
    - imagesize==1.4.1
    - importlib-metadata==5.1.0
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - jmespath==1.0.1
    - joblib==1.2.0
    - jsonnet==0.19.1
    - jsonpickle==3.0.0
    - kiwisolver==1.4.4
    - langcodes==3.3.0
    - lmdb==1.4.0
    - markupsafe==2.1.1
    - matplotlib==3.6.2
    - more-itertools==9.0.0
    - multidict==6.0.3
    - multiprocess==0.70.14
    - murmurhash==1.0.9
    - nltk==3.8
    - numpydoc==1.5.0
    - overrides==3.1.0
    - pandas==1.5.2
    - parsimonious==0.10.0
    - pathtools==0.1.2
    - pathy==0.10.1
    - pillow==9.3.0
    - plac==0.9.6
    - preshed==2.0.1
    - promise==2.3
    - protobuf==3.19.6
    - psutil==5.9.4
    - py-rouge==1.1
    - pyarrow==10.0.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.8.2
    - pygments==2.13.0
    - python-dateutil==2.8.2
    - pytorch-pretrained-bert==0.6.2
    - pytorch-transformers==1.1.0
    - pytz==2022.6
    - pyyaml==6.0
    - regex==2022.10.31
    - requests==2.28.1
    - responses==0.18.0
    - rich==12.6.0
    - rsa==4.9
    - s3transfer==0.6.0
    - sacremoses==0.0.53
    - scikit-learn==1.2.0
    - scipy==1.9.3
    - sentencepiece==0.1.97
    - sentry-sdk==1.11.1
    - setproctitle==1.3.2
    - shortuuid==1.0.11
    - smart-open==6.3.0
    - smmap==5.0.0
    - snowballstemmer==2.2.0
    - spacy==2.1.9
    - spacy-legacy==3.0.10
    - spacy-loggers==1.0.4
    - sphinx==5.3.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - sqlparse==0.4.3
    - srsly==1.0.6
    - tensorboardx==2.5.1
    - termcolor==1.1.0
    - thinc==7.0.8
    - threadpoolctl==3.1.0
    - tokenizers==0.12.1
    - torch==1.13.0
    - tqdm==4.64.1
    - traitlets==5.7.1
    - transformers==4.20.1
    - typer==0.4.2
    - typing-extensions==4.4.0
    - unidecode==1.3.6
    - urllib3==1.26.13
    - wandb==0.12.21
    - wasabi==0.10.1
    - wcwidth==0.2.5
    - werkzeug==2.2.2
    - word2number==1.1
    - xxhash==3.1.0
    - yarl==1.8.2
    - zipp==3.11.0
    - zope-event==4.5.0
    - zope-interface==5.5.2

